// <auto-generated />
using System;
using FinalProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProj.Migrations
{
    [DbContext(typeof(Group_Members_Context))]
    [Migration("20211204025957_Fourth")]
    partial class Fourth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProj.Data.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CareerGoal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteITSubject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearsInIT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerGoal = "Yes",
                            FavoriteITSubject = "Programming",
                            FavoriteLanguage = "C#",
                            YearsInIT = "2"
                        },
                        new
                        {
                            Id = 2,
                            CareerGoal = "Yes",
                            FavoriteITSubject = "Programming",
                            FavoriteLanguage = "C#",
                            YearsInIT = "2"
                        },
                        new
                        {
                            Id = 3,
                            CareerGoal = "Software Analyst",
                            FavoriteITSubject = "Human Computer Interaction",
                            FavoriteLanguage = "C#",
                            YearsInIT = "25"
                        },
                        new
                        {
                            Id = 4,
                            CareerGoal = "QA/Dev",
                            FavoriteITSubject = "Database Management",
                            FavoriteLanguage = "C#",
                            YearsInIT = "3"
                        });
                });

            modelBuilder.Entity("FinalProj.Data.Group_Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2001, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            TeamMemberName = "Riley Setser",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2001, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            TeamMemberName = "JP Kelczewski",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1976, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development/Game Design",
                            TeamMemberName = "Chris Royce",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1997, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            TeamMemberName = "Cooper Siebert",
                            YearInProgram = "Junior"
                        });
                });

            modelBuilder.Entity("FinalProj.Models.FavFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeastFav")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealOfTheDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFav")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteFood = "Hamburgers",
                            LeastFav = "Tomato",
                            MealOfTheDay = "Dinner",
                            SecondFav = "Breakfast Sandwich"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteFood = "Chipotle Burrito",
                            LeastFav = "Cupcakes",
                            MealOfTheDay = "Breakfast",
                            SecondFav = "Bosco Sticks"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteFood = "Chicken and Broccoli Alfredo",
                            LeastFav = "Hot Dogs",
                            MealOfTheDay = "Dinner",
                            SecondFav = "Shrimp Scampi"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteFood = "Chicken Wings",
                            LeastFav = "Sushi",
                            MealOfTheDay = "Lunch",
                            SecondFav = "Burgers"
                        });
                });

            modelBuilder.Entity("FinalProj.Models.Group_Hobbies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Expensive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("TotalSpent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GroupHobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Expensive = "Yes",
                            HobbyName = "Music Producing",
                            StartYear = 2017,
                            TotalSpent = 500
                        },
                        new
                        {
                            Id = 2,
                            Expensive = "Yes",
                            HobbyName = "Golf",
                            StartYear = 2018,
                            TotalSpent = 300
                        },
                        new
                        {
                            Id = 3,
                            Expensive = "Yes",
                            HobbyName = "Gaming",
                            StartYear = 1995,
                            TotalSpent = 5000
                        },
                        new
                        {
                            Id = 4,
                            Expensive = "Yes",
                            HobbyName = "Gaming",
                            StartYear = 2010,
                            TotalSpent = 2000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
