// <auto-generated />
using System;
using FinalProj.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProj.Migrations
{
    [DbContext(typeof(Group_Members_Context))]
    [Migration("20211130183734_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProj.Data.Group_Members", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamMemberName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2001, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            TeamMemberName = "Riley Setser",
                            YearInProgram = "Sophmore"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2001, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            TeamMemberName = "JP Kelczewski",
                            YearInProgram = "Sophmore"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1976, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development/Game Design",
                            TeamMemberName = "Chris Royce",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1997, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Software Development",
                            TeamMemberName = "Cooper Siebert",
                            YearInProgram = "Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
